services:
  db:
    image: postgres:15
    container_name: data_ingestion_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ingestion
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ingestion"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: data_ingestion_service
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/ingestion
